[pytest]
testpaths = tests ros2_ws/src/dynnav_nav2_benchmark/test
pythonpath = . ros2_ws/src/dynnav_nav2_benchmark
norecursedirs = ig_explorer build install log
addopts = --cov=dynnav --cov-report=term-missing -p no:launch-testing -p no:ament_flake8 -p no:ament_copyright -p no:ament_pep257 -p no:ament_lint -p no:ament_xmllint -p no:launch_testing_ros
